language: perl
perl:
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
addons:
  postgresql: 9.6
services:
    - postgresql
env:
  global:
    - TEST_ONLINE=postgresql://postgres@/mojo_test
before_install:
  - sudo apt-get install -y libmagic-dev ruby-sass
install:
  - cpanm -n https://github.com/openSUSE/Spooky-Patterns-XS/archive/1.54.tar.gz
  - cpanm -n --installdeps .
before_script:
  - psql -U postgres -c 'create database mojo_test'
sudo: false
dist: trusty
notifications:
  email: false
